services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pokedev
      POSTGRES_PASSWORD: pokedev
      POSTGRES_DB: pokeprices
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  pgdata: